#!/usr/bin/python
import sys
import numpy as np
import os
import __main__ as main


import pyProbeParticle                as PPU     
from   pyProbeParticle            import basUtils
from   pyProbeParticle            import elements   
import pyProbeParticle.GridUtils      as GU
import pyProbeParticle.HighLevel      as PPH
import pyProbeParticle.fieldFFT       as fFFT
import pyProbeParticle.cpp_utils      as cpp_utils

if __name__=="__main__":
    HELP_MSG="""Use this program in the following way:
    """+os.path.basename(main.__file__) +""" -i <filename> [ --sigma <value> ]
    Supported file fromats are:
       * cube
       * xsf """
    from optparse import OptionParser
    parser = OptionParser()
    parser.add_option( "-i", "--input", action="store", type="string", help="format of input file")
    parser.add_option( "-t", "--tip", action="store", type="string", help="tip model (multipole)", default=None)
    parser.add_option( "-E", "--energy", action="store_true",  help="pbc False", default=False)
    parser.add_option("--noPBC", action="store_false",  help="pbc False",dest="PBC", default=None)
    parser.add_option( "-w", "--sigma", action="store", type="float", help="gaussian width for convolution in Electrostatics [Angstroem]", default=None)
    parser.add_option("-f","--data_format" , action="store" , type="string",help="Specify the output format of the vector and scalar field. Supported formats are: xsf,npy", default="xsf")
    (options, args) = parser.parse_args()
    print options
    opt_dict = vars(options)
    if options.input==None:
        sys.exit("ERROR!!! Please, specify the input file with the '-i' option \n\n"+HELP_MSG)
    print " >> OVEWRITING SETTINGS by params.ini  "
    PPU.loadParams( 'params.ini' )
    PPU.apply_options(opt_dict)
    #print "PPU.params['tip']:",PPU.params['tip']; exit()
    # TODO with time implement reading a hartree potential generated by different software
    iZs,Rs,Qs=None,None,None
    V=None
    atoms,nDim,lvec=basUtils.loadGeometry(options.input, params=PPU.params)
    if os.path.isfile( 'atomtypes.ini' ):
        print ">> LOADING LOCAL atomtypes.ini"  
        FFparams=PPU.loadSpecies( 'atomtypes.ini' ) 
    else:
        FFparams = PPU.loadSpecies( cpp_utils.PACKAGE_PATH+'/defaults/atomtypes.ini' )
    iZs,Rs,Qs=PPH.parseAtoms(atoms, autogeom = False, PBC =PPU.params['PBC'],FFparams=FFparams )
    if ( PPU.params['tip'] == None or PPU.params['tip'] == 's' or PPU.params['tip'] == "s" or PPU.params['tip'] == "'s'"):
        print "point charges only"
        FFel,V=PPH.computeELFF_pch(iZs,Rs,Qs,options.energy)
    else:
        print "point charges and multipole"
        FFel,V=PPH.computeELFF_pch(iZs,Rs,Qs,True)
        del FFel;
        FFel=PPH.computeElFF(V,lvec,nDim[::-1],PPU.params['tip'],Fmax=10.0,computeVpot=options.energy,Vmax=10)

    print " saving electrostatic forcefiled "
    GU.save_vec_field('FFel',FFel,lvec,data_format=options.data_format)
    if options.energy :
        GU.save_scal_field( 'Vel', V, lvec, data_format=options.data_format)
    del FFel,V;
