#! /usr/bin/python

ELEMENTS = [
[	1	,	"H"		,	1	,	1	,	"S"	,	"Hydrogen"	]	,
[	2	,	"He"	,	1	,	0	,	"0"	,	"Helium"	]	,
[	3	,	"Li"	,	2	,	1	,	"S"	,	"Lithium"	]	,
[	4	,	"Be"	,	2	,	2	,	"S"	,	"Beryllium"	]	,
[	5	,	"B"		,	2	,	3	,	"P"	,	"Boron"		]	,
[	6	,	"C"		,	2	,	4	,	"P"	,	"Carbon"	]	,
[	7	,	"N"		,	2	,	5	,	"P"	,	"Nitrogen"	]	,
[	8	,	"O"		,	2	,	6	,	"P"	,	"Oxygen"	]	,
[	9	,	"F"		,	2	,	7	,	"P"	,	"Fluorine"	]	,
[	10	,	"Ne"	,	2	,	0	,	"0"	,	"Neon"		]	,
[	11	,	"Na"	,	3	,	1	,	"S"	,	"Sodium"	]	,
[	12	,	"Mg"	,	3	,	2	,	"S"	,	"Magnesium"	]	,
[	13	,	"Al"	,	3	,	3	,	"P"	,	"Aluminium"	]	,
[	14	,	"Si"	,	3	,	4	,	"P"	,	"Silicon"	]	,
[	15	,	"P"		,	3	,	5	,	"P"	,	"Phosphorus"]	,
[	16	,	"S"		,	3	,	6	,	"P"	,	"Sulfur"	]	,
[	17	,	"Cl"	,	3	,	7	,	"P"	,	"Chlorine"	]	,
[	18	,	"Ar"	,	3	,	0	,	"0"	,	"Argon"		]	,
[	19	,	"K"		,	4	,	1	,	"S"	,	"Potassium"	]	,
[	20	,	"Ca"	,	4	,	2	,	"S"	,	"Calcium"	]	,
[	21	,	"Sc"	,	4	,	3	,	"D"	,	"Scandium"	]	,
[	22	,	"Ti"	,	4	,	4	,	"D"	,	"Titanium"	]	,
[	23	,	"V"		,	4	,	5	,	"D"	,	"Vanadium"	]	,
[	24	,	"Cr"	,	4	,	6	,	"D"	,	"Chromium"	]	,
[	25	,	"Mn"	,	4	,	7	,	"D"	,	"Manganese"	]	,
[	26	,	"Fe"	,	4	,	8	,	"D"	,	"Iron"		]	,
[	27	,	"Co"	,	4	,	9	,	"D"	,	"Cobalt"	]	,
[	28	,	"Ni"	,	4	,	10	,	"D"	,	"Nickel"	]	,
[	29	,	"Cu"	,	4	,	1	,	"D"	,	"Copper"	]	,
[	30	,	"Zn"	,	4	,	2	,	"D"	,	"Zinc"		]	,
[	31	,	"Ga"	,	4	,	3	,	"P"	,	"Gallium"	]	,
[	32	,	"Ge"	,	4	,	4	,	"P"	,	"Germanium"	]	,
[	33	,	"As"	,	4	,	5	,	"P"	,	"Arsenic"	]	,
[	34	,	"Se"	,	4	,	6	,	"P"	,	"Selenium"	]	,
[	35	,	"Br"	,	4	,	7	,	"P"	,	"Bromine"	]	,
[	36	,	"Kr"	,	4	,	0	,	"0"	,	"Krypton"	]	,
[	37	,	"Rb"	,	5	,	1	,	"S"	,	"Rubidium"	]	,
[	38	,	"Sr"	,	5	,	2	,	"S"	,	"Strontium"	]	,
[	39	,	"Y"		,	5	,	3	,	"D"	,	"Yttrium"	]	,
[	40	,	"Zr"	,	5	,	4	,	"D"	,	"Zirconium"	]	,
[	41	,	"Nb"	,	5	,	5	,	"D"	,	"Niobium"	]	,
[	42	,	"Mo"	,	5	,	6	,	"D"	,	"Molybdenum"]	,
[	43	,	"Tc"	,	5	,	7	,	"D"	,	"Technetium"]	,
[	44	,	"Ru"	,	5	,	8	,	"D"	,	"Ruthenium"	]	,
[	45	,	"Rh"	,	5	,	9	,	"D"	,	"Rhodium"	]	,
[	46	,	"Pd"	,	5	,	10	,	"D"	,	"Palladium"	]	,
[	47	,	"Ag"	,	5	,	1	,	"D"	,	"Silver"	]	,
[	48	,	"Cd"	,	5	,	2	,	"D"	,	"Cadmium"	]	,
[	49	,	"In"	,	5	,	3	,	"P"	,	"Indium"	]	,
[	50	,	"Sn"	,	5	,	4	,	"P"	,	"Tin"		]	,
[	51	,	"Sb"	,	5	,	5	,	"P"	,	"Antimony"	]	,
[	52	,	"Te"	,	5	,	6	,	"P"	,	"Tellurium"	]	,
[	53	,	"I"		,	5	,	7	,	"P"	,	"Iodine"	]	,
[	54	,	"Xe"	,	5	,	0	,	"0"	,	"Xenon"		]	,
[	55	,	"Cs"	,	6	,	1	,	"S"	,	"Caesium"	]	,
[	56	,	"Ba"	,	6	,	2	,	"S"	,	"Barium"	]	,
[	57	,	"La"	,	6	,	3	,	"F"	,	"Lanthanum"	]	,
[	58	,	"Ce"	,	6	,	4	,	"F"	,	"Cerium"	]	,
[	59	,	"Pr"	,	6	,	5	,	"F"	,	"Praseodymium"	]	,
[	60	,	"Nd"	,	6	,	6	,	"F"	,	"Neodymium"	]	,
[	61	,	"Pm"	,	6	,	7	,	"F"	,	"Promethium"]	,
[	62	,	"Sm"	,	6	,	8	,	"F"	,	"Samarium"	]	,
[	63	,	"Eu"	,	6	,	9	,	"F"	,	"Europium"	]	,
[	64	,	"Gd"	,	6	,	10	,	"F"	,	"Gadolinium"]	,
[	65	,	"Tb"	,	6	,	11	,	"F"	,	"Terbium"	]	,
[	66	,	"Dy"	,	6	,	12	,	"F"	,	"Dysprosium"]	,
[	67	,	"Ho"	,	6	,	13	,	"F"	,	"Holmium"	]	,
[	68	,	"Er"	,	6	,	14	,	"F"	,	"Erbium"	]	,
[	69	,	"Tm"	,	6	,	1	,	"F"	,	"Thulium"	]	,
[	70	,	"Yb"	,	6	,	2	,	"F"	,	"Ytterbium"	]	,
[	71	,	"Lu"	,	6	,	3	,	"D"	,	"Lutetium"	]	,
[	72	,	"Hf"	,	6	,	4	,	"D"	,	"Hafnium"	]	,
[	73	,	"Ta"	,	6	,	5	,	"D"	,	"Tantalum"	]	,
[	74	,	"W"		,	6	,	6	,	"D"	,	"Tungsten"	]	,
[	75	,	"Re"	,	6	,	7	,	"D"	,	"Rhenium"	]	,
[	76	,	"Os"	,	6	,	8	,	"D"	,	"Osmium"	]	,
[	77	,	"Ir"	,	6	,	9	,	"D"	,	"Iridium"	]	,
[	78	,	"Pt"	,	6	,	10	,	"D"	,	"Platinum"	]	,
[	79	,	"Au"	,	6	,	1	,	"D"	,	"Gold"		]	,
[	80	,	"Hg"	,	6	,	2	,	"D"	,	"Mercury"	]	,
[	81	,	"Tl"	,	6	,	3	,	"P"	,	"Thallium"	]	,
[	82	,	"Pb"	,	6	,	4	,	"P"	,	"Lead"		]	,
[	83	,	"Bi"	,	6	,	5	,	"P"	,	"Bismuth"	]	,
[	84	,	"Po"	,	6	,	6	,	"P"	,	"Polonium"	]	,
[	85	,	"At"	,	6	,	7	,	"P"	,	"Astatine"	]	,
[	86	,	"Rn"	,	6	,	0	,	"0"	,	"Radon"		]	,
[	87	,	"Fr"	,	7	,	1	,	"S"	,	"Francium"	]	,
[	88	,	"Ra"	,	7	,	2	,	"S"	,	"Radium"	]	,
[	89	,	"Ac"	,	7	,	3	,	"F"	,	"Actinium"	]	,
[	90	,	"Th"	,	7	,	4	,	"F"	,	"Thorium"	]	,
[	91	,	"Pa"	,	7	,	5	,	"F"	,	"Protactinium"	]	,
[	92	,	"U"		,	7	,	6	,	"F"	,	"Uranium"	]	,
[	93	,	"Np"	,	7	,	7	,	"F"	,	"Neptunium"	]	,
[	94	,	"Pu"	,	7	,	8	,	"F"	,	"Plutonium"	]	,
[	95	,	"Am"	,	7	,	9	,	"F"	,	"Americium"	]	,
[	96	,	"Cm"	,	7	,	10	,	"F"	,	"Curium"	]	,
[	97	,	"Bk"	,	7	,	11	,	"F"	,	"Berkelium"	]	,
[	98	,	"Cf"	,	7	,	12	,	"F"	,	"Californium"	]	,
[	99	,	"Es"	,	7	,	13	,	"F"	,	"Einsteinium"	]	,
[	100	,	"Fm"	,	7	,	14	,	"F"	,	"Fermium"	]	,
[	101	,	"Md"	,	7	,	1	,	"F"	,	"Mendelevium"	]	,
[	102	,	"No"	,	7	,	2	,	"F"	,	"Nobelium"	]	,
[	103	,	"Lr"	,	7	,	3	,	"D"	,	"Lawrencium"]	,
[	104	,	"Rf"	,	7	,	4	,	"D"	,	"Rutherfordium"	]	,
[	105	,	"Db"	,	7	,	5	,	"D"	,	"Dubnium"	]	,
[	106	,	"Sg"	,	7	,	6	,	"D"	,	"Seaborgium"]	,
[	107	,	"Bh"	,	7	,	7	,	"D"	,	"Bohrium"	]	,
[	108	,	"Hs"	,	7	,	8	,	"D"	,	"Hassium"	]	,
[	109	,	"Mt"	,	7	,	9	,	"D"	,	"Meitnerium"]	,
[	110	,	"Ds"	,	7	,	10	,	"D"	,	"Darmstadtium"	]	,
[	111	,	"Rg"	,	7	,	1	,	"D"	,	"Roentgenium"	]	,
[	112	,	"Uub"	,	7	,	2	,	"D"	,	"Ununbium"	]	
]

def elementDict( ELEMENTS ):
	dic = { }
	for elem in  ELEMENTS:
		dic[ elem[1] ] = elem
	return dic

ELEMENT_DICT = elementDict( ELEMENTS )

